title: Kyu's Portfoilo
name: 황규상
email: hkyku9@naver.com
description: >-
  Data Analist & Digital Marketer


baseurl: ""
url: "https://hkyu3.github.io"


# profile 이미지
profile_image: images/kyusang_casual.jpg


# SNS 아이디
instagram_id: h_kyu3


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_2.jpg
  title: Kyusang <br> Hwang <br> Portfolio site
  subtitle: >- 
    앞으로 더 성장 하고싶은<br>
    데이터 분석가 황규상입니다


# About
about_meta: About Me
about_header: >- 
  "데이터 활용 마케터"
about_introduce: >-
  "안녕하세요. 데이터 활용한 마케팅을 하고자 하는 황규상입니다."
about_content: >-
  아래와 같은 자격을 갖추고 있습니다.
about_services: # 형식에 맞추어 항목 추가
- icon: icon-data
  name: SQL개발자(SQLD)
- icon: icon-monitor
  name: 구글애널리틱스 자격(GAIQ)
- icon: icon-code
  name: 데이터분석준전문가(ADSP)


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content: 앞으로 계속 배워나갈 예정입니다.
tech_list: # 형식에 맞추어 항목 추가
- name: Python
  color: color-1
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: 파이썬을 통한 데이터 전처리부터 데이터 분석 및 시각화가 가능합니다. (머신러닝 & 통계분석)
- name: SQL
  color: color-2
  animation: fadeInRight
  percent: 60
  mark: 60
  content: SQL의 기본적인 문법들을 공부하며, sqld 자격증을 취득했습니다. redash 사이트를 활용하여 가상 회사 데이터 분석 프로젝트를 진행한 경험이 있습니다.
- name: GA
  color: color-3
  animation: fadeInLeft
  percent: 30
  mark: 30
  content: 강의를 통해 Google Analytics 활용 방법을 숙지하며 GAIQ 자격을 취득했습니다. 데모 계정을 통해 개인 프로젝트를 진행한 경험이 있습니다.
- name: Github
  color: color-4
  animation: fadeInRight
  percent: 30
  mark: 30
  content: 프로젝트 진행 시 github를 통해 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다. 또한 github서버를 활용하여 블로그 및 포트폴리오 사이트를 관리합니다.
tech_desc: 


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: <span>팀 프로젝트</span><span>개인 프로젝트</span>
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: #

project_team_name: 팀프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/delivery.png
  animation: fadeInRight
  name: 데이터 안심구역 공모전(2021.09 ~ 2021.11)
  description: 데이터 분석을 통해, 배달관련사고 방지를 위한 서울특별시의 특별 단속구역을 선정하는 프로젝트를 진행했습니다.
  detail_url: https://kyusanghwang0912.github.io/project/2022-02-28-seoul_delivery/

project_my_name: 개인프로젝트
project_my: # 형식에 맞추어 항목 추가
- background_url: images/SQL_comento.png
  animation: fadeInLeft
  name: SQL_redash_데이터 분석 프로젝트
  description: SQL을 활용하여 redash에서 Northwind라는 가상회사의 비즈니스 데이터 분석 프로젝트를 진행했습니다. 
  detail_url: https://kyusanghwang0912.github.io/project/2022-03-01-sql_comento/
  readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 데이터 분석가에게 큰 도움은 되지 않을 수 있지만, 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 광고기획
  color: color-1
  icon: icon-bulb
  content: kobaco의 1인 광고 창작자 양성과정을 통해 광고기획 및 제작을 경험하며 마케터로서의 역량을 키웠습니다. 
- name: 개발
  color: color-2
  icon: icon-home
  content: Django를 활용한 웹사이트 개발 프로젝트 및 융복합 개발 프로젝트에 참여하여 개발 역량을 키웠습니다.
- name : 프로젝트
  color: color-3
  icon: icon-phone3
  content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분이 익숙합니다. 새로운 프로젝트에 도전적입니다.

exp_counters:
- name: project
  count: 2
  speed: 5000


# extracurricular activies
carerr_meta: extracurricular activies
career_header: Work Career
career_list:
- name: kdigital 융복합 프로젝트형 빅데이터 분석 서비스 개발
  date: 2021.06~2021.12
  content: Python Django 웹사이트 개발 프로젝트  <br> Python&R 데이터 분석 알고리즘 학습 및 실습 <br> Bigdata+AI+IoT+Cloud 융복합 개발 프로젝트
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
- name: KOBACO 1인 광고 콘텐츠 창작자 양성과정
  date: 2020.05~2020.09
  content: KOBACO에서 주관하는 교육에서 광고기획 및 제작 프로젝트
  color: color-2
  icon: icon-pen2
  animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: Myungi UNIVERSITY
  subtitle: 명지대학교 산업경영공학과 졸업
  date: 2014.03 - 2021.02
  content: 3.74/4.5
- title: Yongho HIGH SCHOOL
  subtitle: 용호고등학교
  date: 2011.03 - 2014.02


# Blog
blog_meta: self-improvement
blog_header: BLOG
blog_load_more: 발전을 기록하는 중입니다.  # 더보기 내용
blog_load_more_url: #
blog_list:
- title: github 블로그
  subtitle: 데이터 분석 블로그 운영
  date: 2022.01
  content: 깃허브를 통해 개발도 배우며, 커스터마이징이 가능한 블로그를 운영하고 있습니다.
  thumbnail_url: images/blog_logo.png
  link: https://kyusanghwang0912.github.io/
- title: 네이버블로그
  subtitle: 첫 블로그
  date: 2021.01
  content: 본격적으로 python을 배우기 시작할 때 시작한 블로그 입니다.
  thumbnail_url: images/naver_blog_logo.png
  link: https://blog.naver.com/hkyku9


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: hkyku9@naver.com
  icon: icon-globe-outline
- title: 경기도 군포시 산본동
  icon: icon-map
- title: +82 10 5533 9783
  icon: icon-phone
- title: 블로그
  icon: icon-layers2
  url: https://kyusanghwang0912.github.io/

optional_front_matter:
  remove_originals:    true
