title: Kyu's Portfoilo
name: 황규상
email: hkyku9@naver.com
description: >-
  Data Analist


baseurl: ""
url: "https://hkyu3.github.io"


# profile 이미지
profile_image: images/kyusang_casual.jpg


# SNS 아이디
instagram_id: h_kyu3


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_2.jpg
  title: Kyusang <br> Hwang <br> Portfolio site
  subtitle: >- 
    앞으로 더 성장 하고싶은<br>
    데이터 분석가 황규상입니다


# Certificate
about_meta: Certificate
about_header: >- 
  자격증
about_introduce: >-
  "기본적인 자격 요건을 갖춘 데이터 분석가입니다."
about_content: >-
  보유 자격증
about_services: # 형식에 맞추어 항목 추가
- icon: icon-code
  name: 빅데이터분석기사
- icon: icon-data
  name: SQL개발자(SQLD)
- icon: icon-pen
  name: 데이터분석준전문가(ADSP)
- icon: icon-monitor
  name: 구글애널리틱스 자격(GAIQ)



# Tech  skill
tech_meta: TECH SKILLS
tech_header: 활용 기술
about_introduce: >-
  "데이터 분석가가 가져야 할 기술을 갖추었습니다."
tech_content: 활용 기술
tech_list: # 형식에 맞추어 항목 추가
- name: SQL
  color: color-1
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: SQL을 활용하여, 데이터 추출, 가공, 적재가 가능합니다. On-Premise DB의 소스데이터를 활용하여 Cloud DB에 데이터마트를 구축하는 파이프라인을 개발 및 운영한 경험이 있습니다.
- name: Python
  color: color-2
  animation: fadeInRight
  percent: 80
  mark: 80
  content: Python을 활용하여, 내/외부 데이터 수집, 가공, 시각화, 모델링이 가능합니다. 개발한 모델을 활용하여 데이터 수집, 전처리, 예측, 결과적재 파이프라인을 개발 및 운영한 경험이 있습니다.
- name: Tableau
  color: color-3
  animation: fadeInLeft
  percent: 60
  mark: 60
  content: Tableau를 활용하여, 데이터 시각화가 가능합니다. 개발한 모델의 성능 모니터링 및 현업과의 커뮤니케이션을 위해 태블로 대시보드를 개발 및 운영한 경험이 있습니다.
- name: GA
  color: color-4
  animation: fadeInRight
  percent: 50
  mark: 50
  content: 웹 분석 Tool에 대한 기본적인 이해가 있습니다. 예측 모델을 개발할 때, Google analytics의 UV, PV 등의 데이터를 활용한 경험이 있습니다.

#- name: Github
#  color: color-5
#  animation: fadeInLeft
#  percent: 60
#  mark: 60
#  content: 프로젝트 진행 시 github를 통해 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다. 또한 github서버를 활용하여 블로그 및 포트폴리오 사이트를 관리합니다.
tech_desc: 


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: <span>팀 프로젝트</span><span>개인 프로젝트</span>
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: #

project_team_name: 팀프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/delivery.png
  animation: fadeInLeft
  name: 데이터 안심구역 공모전(2021.09 ~ 2021.11)
  description: 데이터 분석을 통해, 배달관련사고 방지를 위한 서울특별시의 특별 단속구역을 선정하는 프로젝트를 진행했습니다.
  detail_url: https://kyusanghwang0912.github.io/project/2022-02-28-seoul_delivery/

- background_url: images/naga.png
  animation: fadeInRight
  name: K-digital 융복합 프로젝트(2021.10 ~ 2021.12)
  description: Bigdata, AI, IoT, Cloud 분야가 협력하여 개발한 무인점포 AI CCTV 제품을 기획하는 프로젝트를 진행했습니다.
  detail_url: https://kyusanghwang0912.github.io/project/2022-02-27-naga/

project_my_name: 개인프로젝트
project_my: # 형식에 맞추어 항목 추가
- background_url: images/SQL_comento.png
  animation: fadeInLeft
  name: SQL_redash_데이터 분석 프로젝트(2022.01 ~ 2022.02)
  description: SQL을 활용하여 redash에서 Northwind라는 가상회사의 비즈니스 데이터 분석 프로젝트를 진행했습니다. 
  detail_url: https://kyusanghwang0912.github.io/project/2022-03-01-sql_comento/
  readmore_url: #

- background_url: images/git_adp.png
  animation: fadeInRight
  name: Pyhton 코딩 북 프로젝트(2021.09 ~ 2022.02)
  description: ADP 자격증 준비를 위해 그룹 스터디를 진행하며 Python을 활용한 전처리/통계분석/머신러닝을 학습 및 실습하고 정리하여, 책으로 제작했습니다.
  detail_url: https://github.com/kyusangHwang0912/TIL/tree/master/ADP
  readmore_url: #



# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 다양한 경험들을 통해 아래와 같은 역량을 키웠습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 데이터 분석
  color: color-1
  icon: icon-bulb
  content: 내부 고객 데이터부터 다양한 외부 데이터를 수집 및 활용하여 모델을 개발 및 운영한 경험을 통해 데이터 분석에 대한 역량을 키웠습니다.
- name: 데이터 엔지니어링
  color: color-2
  icon: icon-phone3
  content: 분석에 필요한 데이터 마트를 구축하기 위해, 데이터 추출, 가공, 적재하는 파이프라인을 개발 및 운영하며 엔지니어링 역량을 키웠습니다.
- name: 커뮤니케이션
  color: color-3
  icon: icon-home
  content: 데이터 분석의 결과를 다양한 현업 담당자들에게 보고 및 공유하는 경험을 통해, 데이터 분석가로서의 커뮤니케이션 역량을 키웠습니다.

exp_counters:
- name: Activities
  count: 4
  speed: 500


# extracurricular activies
carerr_meta: extracurricular activies
career_header: Work Career
career_list:
- name: 한살림 - 데이터 분석가
  date: 2022.05~2023.09
  content: 온라인 수요예측 모델을 개발 및 운영하는 데이터 분석가 <br> - 분석 데이터마트 구축 및 운영 <br> - 수요 예측 모델 개발 및 운영 <br> - On-Premise <-> Cloud 연동되는 수요 예측 파이프라인 개발 및 운영  <br> - 모델 성능평가 및 예측 현황 대시보드 구축 및 운영 <br> - SQL(Oracle), Python, Tableau
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
- name: kdigital 융복합 프로젝트형 빅데이터 분석 서비스 개발
  date: 2021.06~2021.12
  content: 빅데이터 분석, 개발에 필요한 교육 받으며 개인/팀 프로젝트 진행  <br> - 구글Analytics 데모 계정 분석(개인 프로젝트) <br> - 팀 구성 후 데이터 안심구역 경진대회 참여  <br> - 웹페이지 개발(팀 프로젝트) <br> - 융/복합 프로젝트(빅데이터 분석 담당) <br> - Python, R, SQL, Django, Git
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft
- name: 코멘토 SQL 직무부트캠프
  date: 2022.01~2022.02
  content: SQL 문법 교육 및 활용 실습까지 진행하며, 각 주 과제 수행 후 피드백 진행 <br> - Redash의 실습 database의 다양한 실습 문제 해결하는 SQL 쿼리 작성 <br> - SQL 활용한 기업의 데이터 분석 보고서 작성 <br> - SQL 활용한 기업의 대시보드 개발
  color: color-3
  icon: icon-pen2
  animation: fadeInLeft
- name: KOBACO 1인 광고 콘텐츠 창작자 양성과정
  date: 2020.05~2020.09
  content: 광고 기획, 촬영, 편집에 대한 기초 학습 및 팀 프로젝트 진행 <br> - 광고홍보학과, 영화과로 구성된 프로젝트 팀 내 유일한 공과대학 학생으로서 광고 기획에 필요한 데이터 수집 및 분석 과정 담당
  color: color-4
  icon: icon-pen2
  animation: fadeInRight

# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: Myungi UNIVERSITY
  subtitle: 명지대학교 산업경영공학과 졸업
  date: 2014.03 - 2021.02
  content: 3.74/4.5
- title: Yongho HIGH SCHOOL
  subtitle: 용호고등학교
  date: 2011.03 - 2014.02


# Blog
blog_meta: self-improvement
blog_header: BLOG
blog_load_more: 발전을 기록하는 중입니다.  # 더보기 내용
blog_load_more_url: #
blog_list:
- title: github 블로그
  subtitle: 데이터 분석 블로그 운영
  date: 2022.01
  content: 깃허브를 통해 개발도 배우며, 커스터마이징이 가능한 블로그를 운영하고 있습니다.
  thumbnail_url: images/blog_logo.png
  link: https://kyusanghwang0912.github.io/
- title: 네이버블로그
  subtitle: 첫 블로그
  date: 2021.01
  content: 본격적으로 python을 배우기 시작할 때 시작한 블로그 입니다.
  thumbnail_url: images/naver_blog_logo.png
  link: https://blog.naver.com/hkyku9


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: hkyku9@naver.com
  icon: icon-globe-outline
- title: 경기도 군포시 산본동
  icon: icon-map
- title: +82 10 5533 9783
  icon: icon-phone
- title: 블로그
  icon: icon-layers2
  url: https://kyusanghwang0912.github.io/

optional_front_matter:
  remove_originals:    true
