title: Kyu's Portfoilo
name: 황규상
email: hkyku9@naver.com
description: >-
  Data Analyst


baseurl: ""
url: "https://hkyu3.github.io"


# profile 이미지
profile_image: images/kyusang_casual.jpg


# SNS 아이디
# instagram_id: hkyu3

#
linkedin_id : hks912


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_2.jpg
  title: Kyusang <br> Hwang's <br> Portfolio site
  subtitle: >-
    비즈니스 문제를 해결하는<br>
    데이터 분석가 황규상


# Experience
exp_meta: What have I achieved?
exp_header: About me
exp_content: "데이터를 활용해 비즈니스 문제를 해결하고, 가치 있는 의사결정을 만드는 데이터 분석가"
exp_services: # 형식에 맞추어 항목 추가
- name: 3년차 데이터 분석가
  color: color-1
  icon: icon-bulb
  content: 온·오프라인 데이터를 활용하여 수요예측 모델 개발하고 예측 정확도를 개선하는 프로젝트 수행
- name: 데이터 엔지니어링
  color: color-2
  icon: icon-phone3
  content: 온프레미스 및 클라우드 환경에서 데이터 마트 구축 및 ETL 파이프라인을 자동화를 통한 데이터 활용성 증대
- name: 데이터 시각화
  color: color-3
  icon: icon-home
  content: Tableau 기반의 운영 모니터링과 데이터 분석 대시보드 구축을 통한 비즈니스 의사결정 지원



# Tech  skill
tech_meta: TECH SKILLS
tech_header: 주요 기술
tech_content: 데이터 마트 구축부터, 모델 운영 및 대시보드 제공까지의 End-to-End 프로세스 수행
tech_list: # 형식에 맞추어 항목 추가
- name: PYTHON
  color: color-1
  animation: fadeInLeft
  percent: 90
  mark: 90
  content: Python을 활용한 데이터 수집, 전처리, 분석 및 머신러닝 모델 개발 수행. 효율적인 데이터 처리, API 활용을 통한 자동화 파이프라인 구축 경험

- name: SQL
  color: color-2
  animation: fadeInRight
  percent: 90
  mark: 90
  content: SQL을 활용한 데이터 추출, 가공, 적재가 가능. On-Premise 및 Cloud 환경에서 데이터 마트 구축 경험. 테이블 설계, 프로시저 개발, 잡 스케줄링 수행

- name: Tableau
  color: color-3
  animation: fadeInLeft
  percent: 70
  mark: 60
  content: Tableau를 활용한 데이터 분석 및 시각화 수행, 비즈니스 의사결정을 지원하는 대시보드 구축 경험

- name: Pipeline Automation
  color: color-4
  animation: fadeInRight
  percent: 70
  mark: 50
  content: 클라우드 환경에서의 데이터 마트 구축 및 ETL 파이프라인 운영 경험. OCI 기반의 데이터 적재 및 테이블 관리 수행

#- name: Github
#  color: color-5
#  animation: fadeInLeft
#  percent: 60
#  mark: 60
#  content: 프로젝트 진행 시 github를 통해 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다. 또한 github서버를 활용하여 블로그 및 포트폴리오 사이트를 관리합니다.
tech_desc: 


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: 
project_load_more: 위 경험들을 바탕으로, 빠르고 정확하게 배워나가겠습니다.   # 더보기 내용
project_load_more_url: #

project_team_name: 비즈니스 팀 프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/Demand_forecasting_online.png
  animation: fadeInLeft
  name: 온라인 수요예측 모델 개발 프로젝트(2022.06 ~ 2023.11)
  description: 리드타임 단축을 위한 온라인 수요예측 모델 개발 프로젝트
  detail_url: https://broad-morocco-0e4.notion.site/1a1a820339248020a18eeca4c9867281?pvs=4

- background_url: images/Demand_forecasting_offline.png
  animation: fadeInRight
  name: 매장 수요예측 모델 개발 프로젝트(2023.11 ~ 2024.12)
  description: 매장 발주시스템 개선을 위한 수요예측 모델 개발 프로젝트
  detail_url: https://broad-morocco-0e4.notion.site/1a1a8203392480ca9c42e05c30b2ac9e?pvs=4



project_my_name: 개인 프로젝트(공모전 등)
project_my: # 형식에 맞추어 항목 추가
- background_url: images/git_adp.png
  animation: fadeInLeft
  name: 코딩 북 프로젝트(2021.09 ~ 2022.02)
  description: 그룹 스터디를 진행하며 Python을 활용한 전처리,통계분석,머신러닝을 학습 및 실습하고 정리하여, 책으로 제작
  detail_url: https://github.com/kyusangHwang0912/TIL/tree/master/ADP
  readmore_url: #

- background_url: images/delivery.png
  animation: fadeInRight
  name: 데이터 안심구역 공모전(2021.09 ~ 2021.11)
  description: 배달관련사고 방지를 위한 서울특별시의 특별 단속구역 선정 프로젝트
  detail_url: https://kyusanghwang0912.github.io/project/2022-02-28-seoul_delivery/

- background_url: images/naga.png
  animation: fadeInLeft
  name: K-digital 융복합 프로젝트(2021.10 ~ 2021.12)
  description: Bigdata, AI, IoT, Cloud 분야가 협력하여 개발한 무인점포 AI CCTV 제품 기획 프로젝트
  detail_url: https://kyusanghwang0912.github.io/project/2022-02-27-naga/

# - background_url: images/SQL_comento.png
#   animation: fadeInLeft
#   name: SQL_redash_데이터 분석 프로젝트(2022.01 ~ 2022.02)
#   description: SQL을 활용하여 redash에서 Northwind라는 가상회사의 비즈니스 데이터 분석 프로젝트를 진행했습니다. 
#   detail_url: https://kyusanghwang0912.github.io/project/2022-03-01-sql_comento/
#   readmore_url: #



exp_counters:
- name: Career & Activities
  count: 4
  speed: 500


# extracurricula activiesr
carerr_meta: extracurricular activies
career_header: Work Career
career_list:
- name: 한살림 - 데이터 분석가
  date: 2022.05 ~
  content: 매장 수요 예측 모델 개발 및 운영 (2023.11 -) <br> | End-to-End 프로세스 구축 | <br> - 데이터 마트 구축 및 운영 (SQL, Python) <br> - 매장 발주/주문/재고관리 시스템에 적합한 문제 정의 및 데이터 처리 <br> - 주요 변수 탐색 및 모델 최적화  <br> - 매장 수요예측 모델 개발 (자체 모델 / Rule기반 / AutoML) <br> - 모델 학습 및 운영 파이프라인 구축 및 자동화 <br> - API 기반 모니터링 프로세스 구축 (Python - Google Sheet) <br> - 성능평가 대시보드 구축 (Tableau)  <br> <br> 온라인 수요 예측 모델 개발 및 운영 (2022.06 - ) <br> | 데이터 마트 구축 & 모델 개발 및 운영 최적화 | <br> - 데이터 마트 구축 및 운영 (SQL, Python) <br> - 온프레미스 - 클라우드 DB 연동 최적화, 온라인 발주 시스템과 연계 <br> - API 기반 데이터 수집 <br> - 온라인 발주시스템에 적합한 문제 정의 및 데이터 처리 <br> - 온라인 수요예측 모델 개발 (AutoML 활용) <br> - 모델 학습 및 운영 파이프라인 고도화 <br> - 주요 변수 탐색 및 모델 성능 개선 (가설 검증) <br> - 성능 평가 대시보드 구축 (Tableau) <br> <br> 기타 데이터 분석 & 엔지니어링 업무 지원 (2022.06 -) <br> - 클라우드 분석 플랫폼 운영 및 자원 최적화(Oracle Cloud Infrastructure) <br> - API 기반 외부 데이터 수집 및 데이터 마트 구축 <br> - 1,738 물품 사양서 데이터 전산화 → Excel 데이터 파싱 및 전처리 후 적재 <br> - CRM 활동 지원을 위한 데이터 마트 구축(고객, 쿠폰) <br> - 차세대 ERP 시스템 전환 대응 → 테이블 구조 변경 분석 및 데이터 검증
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
- name: kdigital 융복합 프로젝트형 빅데이터 분석 서비스 개발
  date: 2021.06~2021.12
  content: 빅데이터 분석, 개발에 필요한 교육 받으며 개인/팀 프로젝트 진행  <br> - 구글Analytics 데모 계정 분석(개인 프로젝트) <br> - 팀 구성 후 데이터 안심구역 경진대회 참여  <br> - 웹페이지 개발(팀 프로젝트) <br> - 융/복합 프로젝트(빅데이터 분석 담당) <br> - Python, R, SQL, Django, Git
  color: color-2
  icon: icon-pen2
  animation: fadeInLeft
- name: 코멘토 SQL 직무부트캠프
  date: 2022.01~2022.02
  content: SQL 문법 교육 및 활용 실습까지 진행하며, 각 주 과제 수행 후 피드백 진행 <br> - Redash의 실습 database의 다양한 실습 문제 해결하는 SQL 쿼리 작성 <br> - SQL 활용, 데이터 분석 보고서 작성 실습
  color: color-3
  icon: icon-pen2
  animation: fadeInLeft
- name: KOBACO 1인 광고 콘텐츠 창작자 양성과정
  date: 2020.05~2020.09
  content: 광고 기획, 촬영, 편집에 대한 기초 학습 및 팀 프로젝트 진행 <br> - 광고홍보학과, 영화과로 구성된 프로젝트 팀 내 광고 기획에 필요한 데이터 수집 및 분석 과정 담당
  color: color-4
  icon: icon-pen2
  animation: fadeInRight


# Certificate
about_meta: Certificate
about_header: >- 
  자격증
about_introduce: >-
  "데이터 분석에 대한 지식을 보유"
about_content: >-
  보유 자격증
about_services: # 형식에 맞추어 항목 추가
- icon: icon-code
  name: 빅데이터분석기사
- icon: icon-data
  name: SQL개발자(SQLD)
- icon: icon-pen
  name: 데이터분석준전문가(ADSP)
- icon: icon-monitor
  name: 구글애널리틱스 자격(GAIQ)


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: Myungi UNIVERSITY
  subtitle: 명지대학교 산업경영공학과 졸업
  date: 2014.03 - 2021.02
  content: 3.74/4.5
- title: Yongho HIGH SCHOOL
  subtitle: 용호고등학교
  date: 2011.03 - 2014.02


# Blog
blog_meta: self-improvement
blog_header: BLOG
blog_load_more: 발전을 기록하는 중입니다.  # 더보기 내용
blog_load_more_url: #
blog_list:
- title: github 블로그
  subtitle: 데이터 분석 블로그 운영
  date: 2022.01
  content: 커스터마이징이 가능한 블로그를 운영
  thumbnail_url: images/blog_logo.png
  link: https://kyusanghwang0912.github.io/


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: hkyku9@naver.com
  icon: icon-globe-outline
- title: 경기도 군포시 산본동
  icon: icon-map
- title: +82 10 5533 9783
  icon: icon-phone
- title: LinkedIn
  icon: icon-layers2
  url: https://www.linkedin.com/in/hks912/

optional_front_matter:
  remove_originals:    true
